name: ctcl_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  supabase_flutter: ^2.10.0
  mask_text_input_formatter: ^2.9.0
  # fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  assets:
    - .env
  uses-material-design: true
